---
name: 'Twilio Voice Call'
description: 'This GitHub action sends voice call with the defined text.'
branding:
  icon: voicemail
  color: white
inputs:
  twilio_account_sid:
    description: 'Twilio Account SID.'
    required: true
  twilio_auth_token:
    description: 'Twilio Auth token.'
    required: true
  text:
    description: 'Text that will be send by voice call.'
    required: true
  from:
    description: 'Phone number in your Twilio account to send the voice call from.'
    required: true
  to:
    description: 'Phone number to send the voice call to.'
    required: true
  voice:
    description: Call voice.
    required: false
    default: alice
runs:
  using: 'node12'
  main: 'src/index.js'
