---
name: CI

on: push

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2.1.0
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
