---
name: Test

on: push

jobs:
  test:
    name: Test env var
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2.1.0
      - name: Set env var
        run: |
          echo "Failed to test 1"
          echo "Failed to test 2"
          exit 1
      - name: Send report
        if: failure()
        run: |
          echo "${{ toJson(job) }}"
